In [22]:
import pandas as pd
from pandas import read_excel

file_name = 'mf_revenue_prediction.xlsx' 
mf_revenue_prediction = read_excel(file_name)

file_name = 'cc_revenue_prediction.xlsx' 
cc_revenue_prediction = read_excel(file_name)

file_name = 'cl_revenue_prediction.xlsx' 
cl_revenue_prediction = read_excel(file_name)

data = mf_revenue_prediction.merge(cc_revenue_prediction, how="outer", on="Client")
data = data.merge(cl_revenue_prediction, how="outer", on="Client")
data = data.fillna(0)
max_probability =  data[["probability_x", "probability_y", "probability"]].max(axis=1)
data["max_probability"]=max_probability
final_offer = data.sort_values("max_probability", ascending=False)
final_offer = final_offer[:100]
print(final_offer)
final_offer.to_excel("final_offer.xlsx", index=False)

     Client  probability_x  mf_revenue_prediction  probability_y  \
79      529           0.74               2.929343           0.93
192     478           0.00               0.000000           0.93
0      1564           0.92               3.036735           0.00
182    1056           0.62               3.032168           0.00
195     938           0.00               0.000000           0.92
..      ...            ...                    ...            ...
227    1103           0.00               0.000000           0.84
226     374           0.00               0.000000           0.84
12     1337           0.84               3.054669           0.00
224      29           0.00               0.000000           0.84
13      790           0.84               3.053198           0.00

     cc_revenue_prediction  probability  cl_revenue_prediction  \
79                4.482576         0.00               0.000000
192               4.400068         0.00               0.000000
0                 0.000000         0.83              10.667642
182               0.000000         0.92              10.678685
195               5.000517         0.75              11.019265
..                     ...          ...                    ...
227               4.376727         0.00               0.000000
226               4.428268         0.00               0.000000
12                0.000000         0.00               0.000000
224               4.472280         0.00               0.000000
13                0.000000         0.00               0.000000

     max_probability
79              0.93
192             0.93
0               0.92
182             0.92
195             0.92
..               ...
227             0.84
226             0.84
12              0.84
224             0.84
13              0.84

[100 rows x 8 columns]

In [23]:
final_offer

,Client,probability_x,mf_revenue_prediction,probability_y,cc_revenue_prediction,probability,cl_revenue_prediction,max_probability
79,529,0.74,2.929343,0.93,4.482576,0.00,0.000000,0.93
192,478,0.00,0.000000,0.93,4.400068,0.00,0.000000,0.93
0,1564,0.92,3.036735,0.00,0.000000,0.83,10.667642,0.92
182,1056,0.62,3.032168,0.00,0.000000,0.92,10.678685,0.92
195,938,0.00,0.000000,0.92,5.000517,0.75,11.019265,0.92
...,...,...,...,...,...,...,...,...
227,1103,0.00,0.000000,0.84,4.376727,0.00,0.000000,0.84
226,374,0.00,0.000000,0.84,4.428268,0.00,0.000000,0.84
12,1337,0.84,3.054669,0.00,0.000000,0.00,0.000000,0.84
224,29,0.00,0.000000,0.84,4.472280,0.00,0.000000,0.84
13,790,0.84,3.053198,0.00,0.000000,0.00,0.000000,0.84

In [24]:
mf_offer = final_offer[final_offer.probability_x == final_offer.max_probability]
mf_offer = mf_offer[["Client", "probability_x", "mf_revenue_prediction"]]
mf_offer

    Client  probability_x  mf_revenue_prediction
0     1564           0.92               3.036735
2      544           0.91               2.784634
1      556           0.91               3.053878
4     1087           0.90               2.975829
3      390           0.90               2.951082
5      187           0.89               3.066447
6     1182           0.88               3.095037
8     1149           0.87               3.043596
7     1484           0.87               3.047654
10     725           0.86               3.047450
9      416           0.86               3.111932
11     499           0.85               3.044911
15      36           0.84               3.085833
12    1337           0.84               3.054669
13     790           0.84               3.053198

In [25]:
cc_offer = final_offer[final_offer.probability_y == final_offer.max_probability]
cc_offer = cc_offer[["Client", "probability_y", "cc_revenue_prediction"]]
cc_offer

     Client  probability_y  cc_revenue_prediction
79      529           0.93               4.482576
192     478           0.93               4.400068
195     938           0.92               5.000517
193      83           0.92               5.150000
194     322           0.92               4.094715
198    1170           0.91               4.741387
197    1362           0.91               4.148265
196    1406           0.91               3.822676
32     1413           0.91               5.087236
200     963           0.90               4.801341
141    1408           0.90               4.186716
203     908           0.90               3.868913
202     492           0.90               4.401783
201    1522           0.90               4.802243
199     634           0.90               4.873120
205     601           0.89               5.074416
206     694           0.89               4.560917
207     465           0.89               4.271480
91     1571           0.89               4.461576
204    1303           0.89               4.413126
209     449           0.88               4.226393
211    1368           0.88               3.995970
75      372           0.88               4.303364
208    1344           0.88               4.376756
210     230           0.88               3.139134
212     420           0.87               4.921249
215    1178           0.86               4.643958
214     942           0.86               4.288942
219    1330           0.86               4.360992
217     782           0.86               2.282419
216      45           0.86               4.617709
213     569           0.86               4.488768
223    1151           0.85               4.280233
222      68           0.85               4.406918
221     455           0.85               4.289841
220     385           0.85               4.600302
173      43           0.85               4.346973
225     334           0.84               4.461777
232      21           0.84               3.707249
231     219           0.84               4.186595
230     705           0.84               4.414856
229     252           0.84               4.287337
228    1030           0.84               4.373582
227    1103           0.84               4.376727
226     374           0.84               4.428268
224      29           0.84               4.472280

In [26]:
cl_offer = final_offer[final_offer.probability == final_offer.max_probability]
cl_offer = cl_offer[["Client", "probability", "cl_revenue_prediction"]]
cl_offer

     Client  probability  cl_revenue_prediction
182    1056         0.92              10.678685
389    1431         0.91              10.697129
109    1169         0.90              10.728321
390    1231         0.90              10.692662
116     632         0.89              10.690319
184    1175         0.89              11.774022
31      102         0.89              10.683650
392    1513         0.88              10.239042
391    1438         0.88              10.685839
393     491         0.88              10.864255
124     792         0.87              10.660919
394     630         0.87              10.676332
179    1549         0.87              11.503768
218     682         0.87              10.532979
395     380         0.86              10.768210
396    1265         0.86              10.770387
397     225         0.86              10.680511
398     558         0.86              10.670767
399    1591         0.86              10.667712
253     236         0.86              10.684446
64      448         0.86              10.623246
400    1561         0.85              10.615886
405     884         0.85              10.739646
401     838         0.85              10.663919
22      500         0.85              10.474733
356     519         0.85              10.672422
275    1293         0.85              11.097075
406     720         0.85              10.665576
402     642         0.85              10.536027
403    1342         0.85              11.282416
302     384         0.85              10.753849
404     922         0.85              10.737882
411     134         0.84              10.882433
408     906         0.84              10.668763
410    1298         0.84              10.861933
99      775         0.84              14.108321
409    1025         0.84              11.044712
407     691         0.84              10.661499
306     408         0.84              11.124142

In [27]:
mf_offer.to_excel("mf_offer.xlsx", index=False)
cc_offer.to_excel("cc_offer.xlsx", index=False)
cl_offer.to_excel("cl_offer.xlsx", index=False)